name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vlang/setup-v@v1

      - run: v fmt -verify .
      - run: v vet .
      - run: v test .
