name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use v
        uses: takkyuuplayer/vlang-action@master
      - name: fmt and test
        run: |
          v test-fmt
          v -stats test ./
        env:
          CI: true
