name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install v
        run: |
          git clone https://github.com/vlang/v ~/v
          cd ~/v
          make
          sudo ./v symlink
      - uses: actions/checkout@v1
      - name: fmt and test
        run: |
          v test-fmt
          v -stats test ./
        env:
          CI: true
