name: CI

on:
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: vlang/setup-v
      - uses: actions/checkout@v4
      - run: v fmt -verify .
      - run: v vet .
      - run: v test .
