name: Periodic

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: repo
      - name: Build V
        run: |
          make
          sudo ./v symlink

      - name: Compile, Vet, Test
        run: |
          cd repo
          v vet .
          v test .
